// <auto-generated />
using System;
using GalaxisProjectWebAPI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GalaxisProjectWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200916102800_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("GalaxisProjectWebAPI.DataModel.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("CompanyName");

                    b.HasKey("ID");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("GalaxisProjectWebAPI.DataModel.CompanyRepresentative", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CompanyID");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("CompanyRepresentative");
                });

            modelBuilder.Entity("GalaxisProjectWebAPI.DataModel.Fund", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CompanyID");

                    b.Property<double>("FloorLevel");

                    b.Property<string>("FundName");

                    b.Property<string>("InvestmentFundManagerName");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Fund");
                });

            modelBuilder.Entity("GalaxisProjectWebAPI.DataModel.FundToken", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FundID");

                    b.Property<long>("Timestamp");

                    b.Property<int>("TokenID");

                    b.Property<int>("TokenQuantity");

                    b.HasKey("ID");

                    b.HasIndex("FundID")
                        .IsUnique();

                    b.HasIndex("TokenID")
                        .IsUnique();

                    b.ToTable("FundToken");
                });

            modelBuilder.Entity("GalaxisProjectWebAPI.DataModel.Token", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Decimals");

                    b.Property<string>("Name");

                    b.Property<string>("Symbol");

                    b.HasKey("ID");

                    b.ToTable("Token");
                });

            modelBuilder.Entity("GalaxisProjectWebAPI.DataModel.TokenPriceHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("EUR_Price");

                    b.Property<long>("Timestamp");

                    b.Property<int>("TokenID");

                    b.Property<double>("USD_Price");

                    b.HasKey("ID");

                    b.HasIndex("TokenID")
                        .IsUnique();

                    b.ToTable("TokenPriceHistory");
                });

            modelBuilder.Entity("GalaxisProjectWebAPI.DataModel.CompanyRepresentative", b =>
                {
                    b.HasOne("GalaxisProjectWebAPI.DataModel.Company")
                        .WithMany("CompanyRepresentatives")
                        .HasForeignKey("CompanyID");
                });

            modelBuilder.Entity("GalaxisProjectWebAPI.DataModel.Fund", b =>
                {
                    b.HasOne("GalaxisProjectWebAPI.DataModel.Company", "Company")
                        .WithMany("Funds")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GalaxisProjectWebAPI.DataModel.FundToken", b =>
                {
                    b.HasOne("GalaxisProjectWebAPI.DataModel.Fund", "Fund")
                        .WithOne("FundToken")
                        .HasForeignKey("GalaxisProjectWebAPI.DataModel.FundToken", "FundID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GalaxisProjectWebAPI.DataModel.Token", "Token")
                        .WithOne("FundToken")
                        .HasForeignKey("GalaxisProjectWebAPI.DataModel.FundToken", "TokenID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GalaxisProjectWebAPI.DataModel.TokenPriceHistory", b =>
                {
                    b.HasOne("GalaxisProjectWebAPI.DataModel.Token", "Token")
                        .WithOne("TokenPriceHistory")
                        .HasForeignKey("GalaxisProjectWebAPI.DataModel.TokenPriceHistory", "TokenID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
