// <auto-generated />
using GalaxisProjectWebAPI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GalaxisProjectWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200913202304_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("GalaxisProjectWebAPI.DataModel.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("CompanyName");

                    b.HasKey("ID");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("GalaxisProjectWebAPI.DataModel.Fund", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CompanyID");

                    b.Property<double>("FloorLevel");

                    b.Property<string>("FundName");

                    b.Property<string>("InvestmentFundManagerName");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Fund");
                });

            modelBuilder.Entity("GalaxisProjectWebAPI.DataModel.Fund", b =>
                {
                    b.HasOne("GalaxisProjectWebAPI.DataModel.Company", "Company")
                        .WithMany("Funds")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
